export const mealData = [
    {
        "breakfast": {
            "food_name": "Two fried eggs with whole wheat toast and coffee",
            "calories": 400,
            "water": 78,
            "protein": 15,
            "carbohydrates": 30,
            "cholesterol": 370,
            "fibroid": 4,
            "sodium": 300,
            "zinc": 1.5,
            "copper": 0.2,
            "manganese": 0.7,
            "selenium": 33,
            "vitaminA": 500,
            "vitaminC": 0,
            "vitaminD": 2,
            "vitaminE": 1.5,
            "vitaminK": 2,
            "thiamin": 0.2,
            "vitaminB12": 1,
            "imgurl": '/week/Day1/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Steak salad with roasted potatoes, tomatoes, corn, and green onions",
            "calories": 700,
            "water": 120,
            "protein": 40,
            "carbohydrates": 60,
            "cholesterol": 100,
            "fibroid": 10,
            "sodium": 800,
            "zinc": 7,
            "copper": 0.3,
            "manganese": 0.5,
            "selenium": 45,
            "vitaminA": 700,
            "vitaminC": 60,
            "vitaminD": 0,
            "vitaminE": 3,
            "vitaminK": 70,
            "thiamin": 0.3,
            "vitaminB12": 3,
            "imgurl": '/week/Day1/Lunch/lunch.jpg'
        },
        "dinner": {
            "food_name": "Ground beef with bell peppers and rice",
            "calories": 600,
            "water": 100,
            "protein": 30,
            "carbohydrates": 70,
            "cholesterol": 80,
            "fibroid": 5,
            "sodium": 700,
            "zinc": 4,
            "copper": 0.2,
            "manganese": 0.4,
            "selenium": 25,
            "vitaminA": 600,
            "vitaminC": 40,
            "vitaminD": 0,
            "vitaminE": 2,
            "vitaminK": 50,
            "thiamin": 0.2,
            "vitaminB12": 2,
            "imgurl": '/week/Day1/Dinner/dinner.jpg'
        }
    },
    {
        "breakfast": {
            "name": "Mixed Berries with Granola",
            "calories": 200,
            "water": "150g",
            "protein": "4g",
            "carbohydrates": "40g",
            "cholesterol": "0mg",
            "fiber": "8g",
            "sodium": "50mg",
            "zinc": "0.5mg",
            "copper": "0.1mg",
            "manganese": "1mg",
            "selenium": "2mcg",
            "vitaminA": "30IU",
            "vitaminC": "30mg",
            "vitaminD": "0IU",
            "vitaminE": "1mg",
            "vitaminK": "20mcg",
            "thiamin": "0.1mg",
            "vitaminB12": "0mcg",
            "imgurl": '/week/Day2/Breakfast/breakfast.webp'
        },
        "lunch": {
            "name": "Quinoa Salad with Chickpeas, Cucumber, and Cherry Tomatoes",
            "calories": 350,
            "water": "200g",
            "protein": "12g",
            "carbohydrates": "60g",
            "cholesterol": "0mg",
            "fiber": "10g",
            "sodium": "300mg",
            "zinc": "1.5mg",
            "copper": "0.3mg",
            "manganese": "1.5mg",
            "selenium": "5mcg",
            "vitaminA": "50IU",
            "vitaminC": "40mg",
            "vitaminD": "0IU",
            "vitaminE": "2mg",
            "vitaminK": "30mcg",
            "thiamin": "0.2mg",
            "vitaminB12": "0mcg",
            "imgurl": '/week/Day2/Lunch/lunch.webp'
        },
        "dinner": {
            "name": "Grilled Salmon with Broccoli and Sweet Potatoes",
            "calories": 500,
            "water": "250g",
            "protein": "35g",
            "carbohydrates": "45g",
            "cholesterol": "70mg",
            "fiber": "8g",
            "sodium": "400mg",
            "zinc": "2mg",
            "copper": "0.2mg",
            "manganese": "1mg",
            "selenium": "30mcg",
            "vitaminA": "1500IU",
            "vitaminC": "80mg",
            "vitaminD": "400IU",
            "vitaminE": "3mg",
            "vitaminK": "50mcg",
            "thiamin": "0.3mg",
            "vitaminB12": "4mcg",
            "imgurl": '/week/Day2/Dinner/dinner.webp'
        }
    },
    {
        "breakfast": {
            "food_name": "Oatmeal with bananas, walnuts, and honey",
            "calories": 350,
            "water": 72,
            "protein": 7,
            "carbohydrates": 60,
            "cholesterol": 0,
            "fibroid": 6,
            "sodium": 10,
            "zinc": 1.1,
            "copper": 0.2,
            "manganese": 1.5,
            "selenium": 4.5,
            "vitaminA": 10,
            "vitaminC": 10,
            "vitaminD": 0,
            "vitaminE": 0.5,
            "vitaminK": 1.5,
            "thiamin": 0.15,
            "vitaminB12": 0,
            "imgurl": '/week/Day3/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Turkey wrap with avocado, tomato, lettuce, cucumber, and carrot sticks",
            "calories": 400,
            "water": 85,
            "protein": 25,
            "carbohydrates": 45,
            "cholesterol": 35,
            "fibroid": 10,
            "sodium": 600,
            "zinc": 2.5,
            "copper": 0.1,
            "manganese": 0.3,
            "selenium": 18,
            "vitaminA": 100,
            "vitaminC": 30,
            "vitaminD": 0,
            "vitaminE": 2,
            "vitaminK": 20,
            "thiamin": 0.2,
            "vitaminB12": 1,
            "imgurl": '/week/Day3/Lunch/lunch.webp'
        },
        "dinner": {
            "food_name": "Grilled chicken with rice and mixed vegetables",
            "calories": 500,
            "water": 80,
            "protein": 35,
            "carbohydrates": 60,
            "cholesterol": 85,
            "fibroid": 8,
            "sodium": 500,
            "zinc": 3,
            "copper": 0.2,
            "manganese": 0.5,
            "selenium": 25,
            "vitaminA": 150,
            "vitaminC": 40,
            "vitaminD": 0,
            "vitaminE": 1,
            "vitaminK": 30,
            "thiamin": 0.3,
            "vitaminB12": 1.5,
            "imgurl": '/week/Day3/Dinner/dinner.webp'
        }
    },
    {
        "breakfast": {
            "food_name": "Fried eggs with milk and coffee",
            "calories": 350,
            "water": 200,
            "protein": 17,
            "carbohydrates": 10,
            "cholesterol": 425,
            "fibroid": 0,
            "sodium": 200,
            "zinc": 1.5,
            "copper": 0.1,
            "manganese": 0.05,
            "selenium": 32,
            "vitaminA": 550,
            "vitaminC": 0,
            "vitaminD": 2.5,
            "vitaminE": 1.3,
            "vitaminK": 0.3,
            "thiamin": 0.1,
            "vitaminB12": 1.5,
            "imgurl": '/week/Day4/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Ground beef with bell peppers and rice",
            "calories": 600,
            "water": 150,
            "protein": 30,
            "carbohydrates": 70,
            "cholesterol": 80,
            "fibroid": 4,
            "sodium": 700,
            "zinc": 5.5,
            "copper": 0.2,
            "manganese": 0.8,
            "selenium": 25,
            "vitaminA": 300,
            "vitaminC": 40,
            "vitaminD": 0,
            "vitaminE": 1.5,
            "vitaminK": 10,
            "thiamin": 0.2,
            "vitaminB12": 2.5,
            "imgurl": '/week/Day4/Lunch/lunch.webp'
        },
        "dinner": {
            "food_name": "Grilled chicken with quinoa, black beans, and spinach",
            "calories": 700,
            "water": 200,
            "protein": 45,
            "carbohydrates": 70,
            "cholesterol": 90,
            "fibroid": 15,
            "sodium": 600,
            "zinc": 3.5,
            "copper": 0.3,
            "manganese": 1,
            "selenium": 35,
            "vitaminA": 700,
            "vitaminC": 30,
            "vitaminD": 0,
            "vitaminE": 2,
            "vitaminK": 150,
            "thiamin": 0.3,
            "vitaminB12": 3,
            "imgurl": '/week/Day4/Dinner/dinner.webp'
        }
    },
    {
        "breakfast": {
            "food_name": "Green smoothie bowl with mango, spinach, chia seeds, almonds, and sliced almonds",
            "calories": 350,
            "water": 80,
            "protein": 10,
            "carbohydrates": 45,
            "cholesterol": 0,
            "fibroid": 10,
            "sodium": 50,
            "zinc": 1.5,
            "copper": 0.4,
            "manganese": 1.7,
            "selenium": 5,
            "vitaminA": 2500,
            "vitaminC": 50,
            "vitaminD": 0,
            "vitaminE": 4,
            "vitaminK": 150,
            "thiamin": 0.2,
            "vitaminB12": 0,
            "imgurl": '/week/Day5/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Stuffed green peppers with ground beef",
            "calories": 450,
            "water": 70,
            "protein": 30,
            "carbohydrates": 30,
            "cholesterol": 70,
            "fibroid": 8,
            "sodium": 650,
            "zinc": 4,
            "copper": 0.2,
            "manganese": 0.4,
            "selenium": 20,
            "vitaminA": 1000,
            "vitaminC": 120,
            "vitaminD": 0,
            "vitaminE": 1,
            "vitaminK": 20,
            "thiamin": 0.3,
            "vitaminB12": 2,
            "imgurl": '/week/Day5/Lunch/lunch.webp'
        },
        "dinner": {
            "food_name": "Grilled salmon with quinoa and asparagus",
            "calories": 600,
            "water": 75,
            "protein": 45,
            "carbohydrates": 40,
            "cholesterol": 80,
            "fibroid": 7,
            "sodium": 550,
            "zinc": 3,
            "copper": 0.3,
            "manganese": 0.8,
            "selenium": 50,
            "vitaminA": 1200,
            "vitaminC": 30,
            "vitaminD": 10,
            "vitaminE": 2,
            "vitaminK": 60,
            "thiamin": 0.4,
            "vitaminB12": 3,
            "imgurl": '/week/Day5/Dinner/dinner.webp'
        }
    },
    {
        "breakfast": {
            "food_name": "Toast with butter and tea with milk",
            "calories": 250,
            "water": 150,
            "protein": 5,
            "carbohydrates": 30,
            "cholesterol": 15,
            "fibroid": 2,
            "sodium": 300,
            "zinc": 0.5,
            "copper": 0.1,
            "manganese": 0.2,
            "selenium": 10,
            "vitaminA": 200,
            "vitaminC": 0,
            "vitaminD": 1,
            "vitaminE": 0.5,
            "vitaminK": 1,
            "thiamin": 0.1,
            "vitaminB12": 0.5,
            "imgurl": '/week/Day6/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Ground beef with rice and bell peppers",
            "calories": 500,
            "water": 100,
            "protein": 30,
            "carbohydrates": 50,
            "cholesterol": 70,
            "fibroid": 5,
            "sodium": 450,
            "zinc": 5,
            "copper": 0.2,
            "manganese": 0.4,
            "selenium": 25,
            "vitaminA": 300,
            "vitaminC": 70,
            "vitaminD": 0,
            "vitaminE": 2,
            "vitaminK": 15,
            "thiamin": 0.3,
            "vitaminB12": 2,
            "imgurl": '/week/Day6/Lunch/lunch.webp'
        },
        "dinner": {
            "food_name": "Beef steak with rice and mixed vegetables",
            "calories": 600,
            "water": 120,
            "protein": 40,
            "carbohydrates": 55,
            "cholesterol": 90,
            "fibroid": 8,
            "sodium": 500,
            "zinc": 6,
            "copper": 0.3,
            "manganese": 0.5,
            "selenium": 35,
            "vitaminA": 500,
            "vitaminC": 90,
            "vitaminD": 0,
            "vitaminE": 3,
            "vitaminK": 20,
            "thiamin": 0.4,
            "vitaminB12": 3.5,
            "imgurl": '/week/Day6/Dinner/dinner.webp'
        }
    },
    {
        "breakfast": {
            "food_name": "Cinnamon Toast Crunch cereal with milk",
            "calories": 350,
            "water": 200,
            "protein": 8,
            "carbohydrates": 60,
            "cholesterol": 15,
            "fibroid": 3,
            "sodium": 300,
            "zinc": 1.2,
            "copper": 0.1,
            "manganese": 0.1,
            "selenium": 5,
            "vitaminA": 125,
            "vitaminC": 0,
            "vitaminD": 2.5,
            "vitaminE": 1.5,
            "vitaminK": 2,
            "thiamin": 0.3,
            "vitaminB12": 1.2,
            "imgurl": '/week/Day7/Breakfast/breakfast.webp'
        },
        "lunch": {
            "food_name": "Lentil soup with mixed green salad and whole grain bread",
            "calories": 450,
            "water": 250,
            "protein": 16,
            "carbohydrates": 70,
            "cholesterol": 0,
            "fibroid": 15,
            "sodium": 500,
            "zinc": 2.4,
            "copper": 0.3,
            "manganese": 1.2,
            "selenium": 7,
            "vitaminA": 400,
            "vitaminC": 20,
            "vitaminD": 0,
            "vitaminE": 2.5,
            "vitaminK": 35,
            "thiamin": 0.4,
            "vitaminB12": 0,
            "imgurl": '/week/Day7/Lunch/lunch.webp'
        },
        "dinner": {
            "food_name": "Grilled shrimp with couscous and mixed vegetable salad",
            "calories": 500,
            "water": 220,
            "protein": 35,
            "carbohydrates": 55,
            "cholesterol": 130,
            "fibroid": 8,
            "sodium": 600,
            "zinc": 3.5,
            "copper": 0.2,
            "manganese": 0.5,
            "selenium": 30,
            "vitaminA": 450,
            "vitaminC": 25,
            "vitaminD": 0,
            "vitaminE": 3,
            "vitaminK": 45,
            "thiamin": 0.3,
            "vitaminB12": 2.5,
            "imgurl": '/week/Day7/Dinner/dinner.webp'
        }
    }
]
